### ISSUE TITLE
Blokada niezalogowanych 

### ISSUE THREAD

**Issue by Leshens** [Leshens/LetsEatWeb#35]
https://youtu.be/aNMnyLjFqYI?si=VB0ATiUFpbARg5GX
## Dodać
- zablokować dostęp do wszystkich stron oprócz Home, Login, Register dla niezalogowanych
- To samo dla nawbara
- Dodać stronę która będzie się wyświetlać ( i odsyłać do logowania) w momencie kiedy ktoś spróbuje jednak wejść na chronione strony

## Kryteria Akceptacji

- zablokowanie dostępu do chronionych stron

**Comment by sugarvalley** [comment]
niezalogowani maja dostęp tylko do home, login i register,
przy próbie dostania się do np /AdminMenu strona przekierowuje do /Login
